# Generated by Django 2.0 on 2021-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
