# Generated by Django 2.0 on 2021-11-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211108_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stockcode',
        ),
        migrations.AddField(
            model_name='product',
            name='descriptiontest',
            field=models.TextField(blank=True),
        ),
    ]
