# Generated by Django 2.0 on 2021-11-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_descriptiontest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stc',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
