# Generated by Django 2.0 on 2021-11-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_stc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stc',
            new_name='stcstc',
        ),
    ]
