# Generated by Django 2.0 on 2021-11-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211109_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stcstc',
            new_name='stockcode',
        ),
    ]
