# Generated by Django 2.0 on 2021-11-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20211117_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=250)),
                ('Interests', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='product')),
                ('favourite_Fashion_Style', models.TextField(blank=True)),
                ('favourite_Flavour', models.TextField(blank=True)),
                ('favourite_Brand', models.TextField(blank=True)),
                ('favourite_Game_related', models.TextField(blank=True)),
                ('favourite_Movie_Serials_related', models.TextField(blank=True)),
                ('favourite_Books_related', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'customerprofile',
                'verbose_name_plural': 'customerprofiles',
                'ordering': ('name',),
            },
        ),
    ]
