# Generated by Django 2.0 on 2021-11-18 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customerprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ('name',), 'verbose_name': 'customerProfile', 'verbose_name_plural': 'customerProfiles'},
        ),
    ]
