# Generated by Django 2.0 on 2021-11-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211118_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='published_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pulbished_Only_Web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'active'), ('ARCHIVED', 'archived'), ('DRAFT', 'draft')], max_length=3),
        ),
    ]
