# Generated by Django 2.0 on 2021-11-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20211118_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='stockcode',
            new_name='SKU',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stockcode',
            new_name='SKU',
        ),
    ]
