# Generated by Django 2.0 on 2021-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211118_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_Number', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('ProductSKU', models.CharField(blank=True, max_length=250)),
                ('product_Title', models.CharField(blank=True, max_length=250)),
                ('POImage', models.ImageField(blank=True, upload_to='product')),
                ('PIImage', models.ImageField(blank=True, upload_to='product')),
                ('GRNImage', models.ImageField(blank=True, upload_to='product')),
                ('QTY', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmPO', models.BooleanField(default=True)),
                ('confirmPODate', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'purchaseOrder',
                'verbose_name_plural': 'purchaseOrders',
                'ordering': ('PO_Number',),
            },
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='retail_Price',
        ),
        migrations.RemoveField(
            model_name='category',
            name='SKU',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
