# Generated by Django 2.0 on 2021-11-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211119_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ('name',), 'verbose_name': 'customer_Profile', 'verbose_name_plural': 'customer_Profiles'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ('PO_Number',), 'verbose_name': 'purchase_Order', 'verbose_name_plural': 'purchase_Orders'},
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='ProductSKU',
            new_name='product_SKU',
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='confirmPO',
            field=models.BooleanField(default=False),
        ),
    ]
