# Generated by Django 2.0 on 2021-11-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211119_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='name',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
