# Generated by Django 2.0 on 2021-11-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_purchaseorder_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='confirmPO',
            new_name='confirm_PO',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='confirmPODate',
            new_name='confirm_PO_Date',
        ),
    ]
