# Generated by Django 2.0 on 2021-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20211119_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'test_Order',
                'verbose_name_plural': 'test_Order',
                'ordering': ('id',),
            },
        ),
    ]
