# Generated by Django 2.0 on 2021-11-23 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_testorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='logistic_Cost',
        ),
        migrations.RemoveField(
            model_name='product',
            name='logistic_Vendor',
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Vendor_Invoice',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='Vendor_Receipt',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistic_Cost',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistic_Invoice',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistic_Receipt',
            field=models.ImageField(blank=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='logistic_Vendor',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
