# Generated by Django 2.0 on 2021-11-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211123_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='retail_Price',
            new_name='price',
        ),
    ]
