# Generated by Django 2.0 on 2021-11-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20211127_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Cat_ID',
            new_name='CatID',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Retail Price'),
        ),
    ]
