# Generated by Django 2.0 on 2021-11-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211127_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='published_At',
        ),
        migrations.RemoveField(
            model_name='category',
            name='pulbished_Only_Web',
        ),
        migrations.AddField(
            model_name='category',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='category',
            name='pulbishedOnlyWeb',
            field=models.BooleanField(default=False, verbose_name='Published Only Web'),
        ),
    ]
