# Generated by Django 2.0 on 2021-11-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20211127_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, unique=True)),
                ('PONumber', models.CharField(max_length=250, unique=True, verbose_name='PO Number')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('productSKU', models.CharField(blank=True, max_length=250, verbose_name='Product SKU')),
                ('qty', models.IntegerField(verbose_name='QTY')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productTitle', models.CharField(blank=True, max_length=250, verbose_name='Product Title')),
                ('POImage', models.ImageField(blank=True, upload_to='product', verbose_name='PO Image')),
                ('PIImage', models.ImageField(blank=True, upload_to='product', verbose_name='PI Image')),
                ('GRNImage', models.ImageField(blank=True, upload_to='product', verbose_name='Goods Received Note GRN Image')),
                ('VendorInvoice', models.ImageField(blank=True, upload_to='product', verbose_name='Vendor Invoice')),
                ('VendorReceipt', models.ImageField(blank=True, upload_to='product', verbose_name='Vendor Receipt')),
                ('logisticVendor', models.CharField(blank=True, max_length=250, verbose_name='Logistic Vendor')),
                ('logisticCost', models.CharField(blank=True, max_length=250, verbose_name='Logistic Cost')),
                ('logisticInvoice', models.ImageField(blank=True, upload_to='product', verbose_name='Logistic Invoice')),
                ('logisticReceipt', models.ImageField(blank=True, upload_to='product', verbose_name='Logistic Receipt')),
                ('confirmPO', models.BooleanField(default=False, verbose_name='Confirm PO')),
                ('confirmPODate', models.DateTimeField(auto_now=True, verbose_name='Confirm PO Date')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Stock Purchase Order',
                'verbose_name_plural': 'Stock Purchase Orders',
                'ordering': ('PONumber',),
            },
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Books_related',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Brand',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Fashion_Style',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Flavour',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Game_related',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favourite_Movie_Serials_related',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_Feedback',
        ),
        migrations.RemoveField(
            model_name='product',
            name='published_At',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pulbished_Only_Web',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouritBrand',
            field=models.TextField(blank=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouriteBooksRelated',
            field=models.TextField(blank=True, verbose_name='Books related'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouriteFashionStyle',
            field=models.TextField(blank=True, verbose_name='FashionStyle'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouriteFlavour',
            field=models.TextField(blank=True, verbose_name='Flavour'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouriteGameRelated',
            field=models.TextField(blank=True, verbose_name='Game related'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favouriteMovieSerialsRelated',
            field=models.TextField(blank=True, verbose_name='Movie Serial related'),
        ),
        migrations.AddField(
            model_name='product',
            name='customerFeedback',
            field=models.TextField(blank=True, verbose_name='Customer Feedback'),
        ),
        migrations.AddField(
            model_name='product',
            name='publishedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='product',
            name='pulbishedOnlyWeb',
            field=models.BooleanField(default=False, verbose_name='Published Only Web'),
        ),
    ]
