# Generated by Django 2.0 on 2021-11-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='giftcardnumber',
            field=models.CharField(blank=True, max_length=250, verbose_name='Gift Card Number'),
        ),
    ]
