# Generated by Django 2.0 on 2021-11-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20211130_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pricerule',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
