# Generated by Django 2.0 on 2021-11-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20211130_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='pricerule',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
