# Generated by Django 2.0 on 2021-11-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='test',
        ),
        migrations.AddField(
            model_name='product',
            name='stockcode',
            field=models.CharField(default='', max_length=250, unique=True),
        ),
    ]
