# Generated by Django 2.0 on 2021-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211107_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stockcode',
            field=models.CharField(default='', max_length=250),
        ),
    ]
