# Generated by Django 2.0 on 2021-11-07 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211107_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stockcode',
        ),
    ]
