# Generated by Django 2.0 on 2021-11-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_stockcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='descriptiontest',
            field=models.TextField(blank=True),
        ),
    ]
